Repository cerdeuk/CERTI-ANDROID, pull requests merged in 2025-07, with the labels that each got.

#11 [Setting/#10] ColorSystem 세팅
  app/src/main/java/org/sopt/certi/ui/theme/Color.kt
  app/src/main/java/org/sopt/certi/ui/theme/Theme.kt
Labels: ⚙️ Init, 😎 종우

#9 [Setting/#8] Font 설정
  app/src/main/java/org/sopt/certi/ui/theme/Theme.kt
  app/src/main/java/org/sopt/certi/ui/theme/Type.kt
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
Labels: ⚙️ Init, 💜 민지

#13 [Setting/#12] theme 세팅
  app/src/main/java/org/sopt/certi/ui/theme/Theme.kt
Labels: ⚙️ Init, 😎 종우

#17 [Add/#14] 에셋 추가
  app/src/main/res/drawable/ic_arrowdown_24.xml
  app/src/main/res/drawable/ic_arrowleft_36.xml
  app/src/main/res/drawable/ic_arrowright_24.xml
  app/src/main/res/drawable/ic_arrowright_36.xml
  app/src/main/res/drawable/ic_arrowup_24.xml
  app/src/main/res/drawable/ic_category_24.xml
  app/src/main/res/drawable/ic_certi_emogi_50_1.xml
  app/src/main/res/drawable/ic_certi_emoji_50_2.xml
  app/src/main/res/drawable/ic_certi_emoji_50_3.xml
  app/src/main/res/drawable/ic_certification_16.xml
  app/src/main/res/drawable/ic_check_16.xml
  app/src/main/res/drawable/ic_check_24.xml
  app/src/main/res/drawable/ic_close_24.xml
  app/src/main/res/drawable/ic_close_36.xml
  app/src/main/res/drawable/ic_date_16.xml
  app/src/main/res/drawable/ic_date_24.xml
  app/src/main/res/drawable/ic_home_24.xml
  app/src/main/res/drawable/ic_link_16.xml
  app/src/main/res/drawable/ic_modalclose_24.xml
  app/src/main/res/drawable/ic_paper_16.xml
  app/src/main/res/drawable/ic_progresscheck_48.xml
  app/src/main/res/drawable/ic_recommendation_24.xml
  app/src/main/res/drawable/ic_resume_24.xml
  app/src/main/res/drawable/ic_search_24.xml
  app/src/main/res/drawable/ic_star_24.xml
  app/src/main/res/drawable/img_certification_card_get.png
  app/src/main/res/drawable/img_empty.png
  app/src/main/res/drawable/img_firework.png
  app/src/main/res/drawable/img_google_login.png
  app/src/main/res/drawable/img_kakao_login.png
  app/src/main/res/drawable/img_login.png
  app/src/main/res/drawable/img_logo.png
  app/src/main/res/drawable/img_logo_black.png
  app/src/main/res/drawable/img_logo_white.png
  app/src/main/res/drawable/img_onboarding_firework.png
  app/src/main/res/drawable/img_onboarding_image_small.png
  app/src/main/res/drawable/img_onboarding_progressbar_1.png
  app/src/main/res/drawable/img_onboarding_progressbar_2.png
  app/src/main/res/drawable/img_onboarding_progressbar_3.png
  app/src/main/res/drawable/img_onboarding_progressbar_4.png
  app/src/main/res/drawable/img_onboarding_progressbar_5.png
  app/src/main/res/drawable/img_profile.png
  app/src/main/res/drawable/img_splash_logo.png
Labels: ➕ Add, 🍀 지현

#22 [Feat/#19] 공통컴포넌트 - 바텀네비게이션바 구현
  app/src/main/java/org/sopt/certi/presentation/ui/main/MainBottomBar.kt
  app/src/main/java/org/sopt/certi/presentation/ui/main/MainTab.kt
  app/src/main/res/drawable/ic_resume_24.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🌀 민서

#23 [Feat/#21] 공통컴포넌트 - 텍스트필드 구현
  app/src/main/java/org/sopt/certi/core/component/DummyComponent.kt
  app/src/main/java/org/sopt/certi/core/component/button/CertiBasicButton.kt
  app/src/main/java/org/sopt/certi/core/component/textfield/CertiBasicTextField.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🌀 민서

#26 [Feat/#20] 공통 컴포넌트 - 삭제 다이얼로그 구현
  app/src/main/java/org/sopt/certi/core/component/dialog/CertiDeleteDialog.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🍀 지현

#25 [Feat/#18] 공통컴포넌트 - tag chip default 구현
  app/src/main/java/org/sopt/certi/core/component/chip/CertiDefaultChip.kt
Labels: ✨ Feat, 💜 민지

#28 [Feat/#24] 공통컴포넌트 - 자격증 리스트 섹션 구현
  app/src/main/java/org/sopt/certi/core/component/section/CertificationListSection.kt
  app/src/main/java/org/sopt/certi/core/component/textfield/CertiBasicTextField.kt
  app/src/main/java/org/sopt/certi/domain/model/CertificationListData.kt
Labels: ✨ Feat, 🌀 민서

#32 [Feat/#29] 소셜 로그인(카카오) 세팅, 로그인 뷰 UI 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/certi/CERTIApp.kt
  app/src/main/java/org/sopt/certi/presentation/type/DummyType.kt
  app/src/main/java/org/sopt/certi/presentation/type/SocialLoginType.kt
  app/src/main/java/org/sopt/certi/presentation/ui/login/LoginScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/login/LoginViewModel.kt
  app/src/main/java/org/sopt/certi/presentation/ui/login/component/BouncingImage.kt
  app/src/main/java/org/sopt/certi/presentation/ui/login/component/SocialLoginButton.kt
  app/src/main/res/drawable/img_bouncing_login.png
  app/src/main/res/drawable/img_login.png
  app/src/main/res/drawable/img_login_shadow.png
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: ✨ Feat, 🔎 UI, 🌀 민서

#33 [Feat/#27] 희망분야 재설정 칩 구현
  app/src/main/java/org/sopt/certi/core/component/chip/ReselectInterestedChip.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 😎 종우

#44 [Feat/#35] 프로필 정보 섹션 구현
  app/src/main/java/org/sopt/certi/domain/model/UserInfoData.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/component/UserInfoSection.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 💜 민지

#52 [Feat/#47] 취득 예정 자격증 컴포넌트 구현
  app/src/main/java/org/sopt/certi/domain/model/PreCertificationData.kt
  app/src/main/java/org/sopt/certi/presentation/type/CertiEmojiType.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/component/PreCertificationItem.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 💜 민지

#55 [Feat/#45] 이력서 희망 직무 컴포넌트 구현
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeProfile.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🍀 지현

#66 [Feat/#62] 추천 자격증 컴포넌트 구현
  app/src/main/java/org/sopt/certi/domain/model/RecommendedCertificationData.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/component/RecommendedCertificationItem.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 💜 민지

#59 [Feat/#43] 이력서 자격증 카드
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeCertificationSmallCard.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeDescriptionSection.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🍀 지현

#67 [fix/#69] 컴포넌트 비율 적용
  app/src/main/java/org/sopt/certi/core/component/dialog/CertiDeleteDialog.kt
  app/src/main/java/org/sopt/certi/core/component/topbar/CertiTopBar.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeDescriptionSection.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeEditListItem.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeInputSection.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeInputTitle.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeListItem.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeTextField.kt
Labels: ♻️ Refactor, 🍀 지현

#78 [Feat/#70] 온보딩 뷰 UI 구현
  app/src/main/java/org/sopt/certi/core/component/chip/CertiDefaultChip.kt
  app/src/main/java/org/sopt/certi/domain/model/UserInfoData.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/component/UserInfoSection.kt
  app/src/main/java/org/sopt/certi/presentation/ui/login/LoginScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/onboarding/OnBoardingGradeScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/onboarding/OnBoardingInfoScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/onboarding/OnBoardingJobCategoryScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/onboarding/OnBoardingMajorScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/onboarding/OnBoardingTrackScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/onboarding/OnBoardingUnivScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/splash/SplashScreen.kt
  app/src/main/res/drawable/img_onboarding_progressbar_1.png
  app/src/main/res/drawable/img_onboarding_progressbar_2.png
  app/src/main/res/drawable/img_onboarding_progressbar_3.png
  app/src/main/res/drawable/img_onboarding_progressbar_4.png
  app/src/main/res/drawable/img_onboarding_progressbar_5.png
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🔎 UI, 🌀 민서

#75 [Feat/#60] 이력서 메인화면 섹션 구현
  app/src/main/java/org/sopt/certi/domain/model/ResumeCertificationListData.kt
  app/src/main/java/org/sopt/certi/domain/model/ResumeListData.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/CertiEmptySection.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeCertificationSection.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeCertificationSmallCard.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeDescriptionSection.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeEditListItem.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeInputTitle.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeListContent.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeListItem.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeListSection.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeProfile.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeTextField.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeTextInputSection.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🍀 지현

#86 [Feat/#83] 카테고리 뷰 UI 구현
  app/src/main/java/org/sopt/certi/domain/model/CertificationListData.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certlist/CertListScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certlist/component/CategoryFavoriteButton.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certlist/component/CategoryTopBar.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🔎 UI, 🌀 민서

#89 [Feat/#72] 자격증 취득 완료 dialog 구현
  app/src/main/java/org/sopt/certi/core/component/dialog/CertAcquiredDialog.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 😎 종우

#90 [Feat/#85] 이력서 추가 버튼
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeAddButton.kt
  app/src/main/res/drawable/ic_resume_add_24.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🍀 지현

#97 [Feat/#88] 검색 뷰 UI 구현
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/org/sopt/certi/core/component/section/CertiEmptySection.kt
  app/src/main/java/org/sopt/certi/core/component/section/CertificationListSection.kt
  app/src/main/java/org/sopt/certi/core/component/textfield/CertiBasicTextField.kt
  app/src/main/java/org/sopt/certi/domain/model/ActivityData.kt
  app/src/main/java/org/sopt/certi/domain/model/CertificationListData.kt
  app/src/main/java/org/sopt/certi/domain/model/FavoriteCertificationData.kt
  app/src/main/java/org/sopt/certi/domain/model/PreCertificationData.kt
  app/src/main/java/org/sopt/certi/domain/model/RecommendedCertificationData.kt
  app/src/main/java/org/sopt/certi/domain/model/ResumeCertificationListData.kt
  app/src/main/java/org/sopt/certi/domain/model/ResumeData.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certlist/CertListScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certlist/navigation/CertListNavigation.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/component/FavoriteCertificationItem.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/component/PreCertificationItem.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/component/RecommendedCertificationItem.kt
  app/src/main/java/org/sopt/certi/presentation/ui/main/MainNavHost.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/ResumeScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeCertificationSection.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeCertificationSmallCard.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeDescriptionSection.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeEditListItem.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeListContent.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeListSection.kt
  app/src/main/java/org/sopt/certi/presentation/ui/search/SearchScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/search/SearchViewModel.kt
  app/src/main/java/org/sopt/certi/presentation/ui/search/navigation/SearchNavigation.kt
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🔎 UI, 🌀 민서

#102 [Feat/#96] 경력사항 뷰 UI 구현
  app/src/main/java/org/sopt/certi/core/navigation/RouteModel.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/ResumeAddWorkExperienceScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/ResumeWorkExperienceScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeAddButton.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeDateInputSection.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeEditListItem.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeMyCertiListItem.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeTextField.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/navigation/ResumeNavigation.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🔎 UI, 🍀 지현

#106 [Feat/#99] 카테고리 뷰 로직 구현
  app/src/main/java/org/sopt/certi/presentation/ui/certlist/CertListScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certlist/CertListViewModel.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certlist/state/CertListUiState.kt
Labels: ✨ Feat, 🌀 민서

#108 [Feat/#105] 자격증 상세정보 UI 구현
  app/src/main/java/org/sopt/certi/core/component/button/CertiBasicButton.kt
  app/src/main/java/org/sopt/certi/core/component/webview/CertWebView.kt
  app/src/main/java/org/sopt/certi/core/util/Formatter.kt
  app/src/main/java/org/sopt/certi/domain/model/CertificationData.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certdetail/CertDetailScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certdetail/component/button/CertDetailButton.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certdetail/component/button/MoveToWebButton.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certdetail/navigation/CertDetailNavigation.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certrecommend/CertRecommendScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/main/MainNavHost.kt
  app/src/main/res/drawable/ic_clock_16.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 🔎 UI, 😎 종우

#109 [Feat/#107] 이력서-자격증 카드 뒤집기 애니메이션 구현
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/card/CertificationCardBack.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/card/CertificationCardFront.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/card/FlipCard.kt
Labels: ✨ Feat, 💜 민지

#117 [Feat/#115] 카드 뒤집는 애니메이션 구현
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/AcquiredDateChip.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/card/CertificationCardBack.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/card/CertificationCardFront.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/card/FlipCard.kt
  app/src/main/res/values/strings.xml
Labels: ✨ Feat, 💜 민지

#119 [Feat/#111] 온보딩 뷰 로직 구현
  app/src/main/java/org/sopt/certi/presentation/ui/onboarding/OnBoardingGradeScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/onboarding/OnBoardingInfoScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/onboarding/OnBoardingJobCategoryScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/onboarding/OnBoardingMajorScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/onboarding/OnBoardingTrackScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/onboarding/OnBoardingUnivScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/onboarding/OnBoardingViewModel.kt
  app/src/main/java/org/sopt/certi/presentation/ui/onboarding/state/OnBoardingMajorUiState.kt
  app/src/main/java/org/sopt/certi/presentation/ui/onboarding/state/OnBoardingUnivUiState.kt
Labels: ✨ Feat, 🌀 민서

#122 [Feat/#118] 홈화면 로직 구현
  app/src/main/java/org/sopt/certi/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/component/FavoriteCertificationItem.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/state/HomeUiState.kt
Labels: ✨ Feat, 💜 민지

#127 [Feat/#121] 추천 리스트 로직 구현
  app/src/main/java/org/sopt/certi/domain/type/CategoryType.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certrecommend/CertRecommendScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certrecommend/CertRecommendViewModel.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certrecommend/sideeffect/RecommendSideEffect.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certrecommend/state/RecommendUiState.kt
Labels: ✨ Feat, 😎 종우

#126 [Feat/#123] 취득 예정 자격증 편집 화면 로직 구현
  app/src/main/java/org/sopt/certi/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/PreCertificationEditScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/org/sopt/certi/presentation/ui/precertificationedit/PreCertiEditViewModel.kt
  app/src/main/java/org/sopt/certi/presentation/ui/precertificationedit/PreCertificationEditScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/precertificationedit/component/PreCertificationItem.kt
  app/src/main/java/org/sopt/certi/presentation/ui/precertificationedit/state/PreCertiEditUiState.kt
Labels: ✨ Feat, 💜 민지

#136 [Feat/#130] 이력서 경력사항 뷰 로직 구현
  app/src/main/java/org/sopt/certi/domain/model/ActivityData.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/ResumeActivitiesScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeDescriptionSection.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeEditListItem.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeListContent.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeListSection.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/main/ResumeScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/main/ResumeViewModel.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/main/sideEffect/ResumeSideEffect.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/myCert/ResumeMyCertScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/navigation/ResumeNavigation.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/workExperience/AddWorkExperienceViewModel.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/workExperience/ResumeAddWorkExperienceScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/workExperience/ResumeWorkExperienceScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/workExperience/WorkExperienceViewModel.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/workExperience/sideEffect/WorkExperienceSideEffect.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/workExperience/state/AddWorkExperienceUiState.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/workExperience/state/WorkExperienceUiState.kt
Labels: ✨ Feat, 🍀 지현

#138 [Feat/#137] 이력서 대내외활동 로직 구현
  app/src/main/java/org/sopt/certi/presentation/ui/resume/activity/ActivityViewModel.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/activity/AddActivityViewModel.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/activity/ResumeActivitiesScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/activity/ResumeAddActivitiesScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/activity/sideEffect/ActivitySideEffect.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/activity/state/ActivityUiState.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/activity/state/AddActivityUiState.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/navigation/ResumeNavigation.kt
Labels: ✨ Feat, 🍀 지현

#146 [Feat #143] 자격증 상세정보 화면 API 연동
  app/src/main/java/org/sopt/certi/data/mapper/todomain/cert/CertInfoResponseDtoMapper.kt
  app/src/main/java/org/sopt/certi/data/remote/datasource/AcquisitionRemoteDataSource.kt
  app/src/main/java/org/sopt/certi/data/remote/datasource/CertRemoteDataSource.kt
  app/src/main/java/org/sopt/certi/data/remote/datasource/PreCertRemoteDataSource.kt
  app/src/main/java/org/sopt/certi/data/remote/datasourceimpl/AcquisitionRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/certi/data/remote/datasourceimpl/CertRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/certi/data/remote/datasourceimpl/PreCertRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/certi/data/remote/dto/response/GetCertInfoResponseDto.kt
  app/src/main/java/org/sopt/certi/data/remote/service/AcquisitionService.kt
  app/src/main/java/org/sopt/certi/data/remote/service/CertService.kt
  app/src/main/java/org/sopt/certi/data/remote/service/PreCertService.kt
  app/src/main/java/org/sopt/certi/data/repositoryimpl/AcquisitionRepositoryImpl.kt
  app/src/main/java/org/sopt/certi/data/repositoryimpl/CertRepositoryImpl.kt
  app/src/main/java/org/sopt/certi/data/repositoryimpl/PreCertRepositoryImpl.kt
  app/src/main/java/org/sopt/certi/di/DataSourceModule.kt
  app/src/main/java/org/sopt/certi/di/RepositoryModule.kt
  app/src/main/java/org/sopt/certi/di/ServiceModule.kt
  app/src/main/java/org/sopt/certi/di/UseCaseModule.kt
  app/src/main/java/org/sopt/certi/domain/model/certification/CertificationData.kt
  app/src/main/java/org/sopt/certi/domain/repository/AcquisitionRepository.kt
  app/src/main/java/org/sopt/certi/domain/repository/CertRepository.kt
  app/src/main/java/org/sopt/certi/domain/repository/PreCertRepository.kt
  app/src/main/java/org/sopt/certi/domain/usecase/acquisition/AcquiredCertUseCase.kt
  app/src/main/java/org/sopt/certi/domain/usecase/certification/GetCertInfoUseCase.kt
  app/src/main/java/org/sopt/certi/domain/usecase/precert/AcquireExpectCertUseCase.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certdetail/CertDetailScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certdetail/CertDetailViewModel.kt
Labels: 💻 API 연결, 😎 종우

#147 [Feat/#145] 대내외활동, 경력사항 추가 API 연결
  app/src/main/java/org/sopt/certi/data/remote/datasource/ActivityRemoteDataSource.kt
  app/src/main/java/org/sopt/certi/data/remote/datasource/CareerRemoteDataSource.kt
  app/src/main/java/org/sopt/certi/data/remote/datasourceimpl/ActivityRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/certi/data/remote/datasourceimpl/CareerRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/certi/data/remote/dto/request/AddActivityCareerRequestDto.kt
  app/src/main/java/org/sopt/certi/data/remote/service/ActivityService.kt
  app/src/main/java/org/sopt/certi/data/remote/service/CareerService.kt
  app/src/main/java/org/sopt/certi/data/repositoryimpl/ActivityRepositoryImpl.kt
  app/src/main/java/org/sopt/certi/data/repositoryimpl/CareerRepositoryImpl.kt
  app/src/main/java/org/sopt/certi/di/DataSourceModule.kt
  app/src/main/java/org/sopt/certi/di/RepositoryModule.kt
  app/src/main/java/org/sopt/certi/di/ServiceModule.kt
  app/src/main/java/org/sopt/certi/di/UseCaseModule.kt
  app/src/main/java/org/sopt/certi/domain/repository/ActivityRepository.kt
  app/src/main/java/org/sopt/certi/domain/repository/CareerRepository.kt
  app/src/main/java/org/sopt/certi/domain/usecase/AddActivityUseCase.kt
  app/src/main/java/org/sopt/certi/domain/usecase/AddCareerUseCase.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certlist/CertListScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/certlist/navigation/CertListNavigation.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/activity/AddActivityViewModel.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/activity/ResumeAddActivitiesScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/workExperience/AddWorkExperienceViewModel.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/workExperience/ResumeAddWorkExperienceScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/search/SearchScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/search/navigation/SearchNavigation.kt
Labels: ✨ Feat, 💻 API 연결, 🌀 민서

#149 [Feat/#148] keystore 작업
  .gitignore
  app/build.gradle.kts
  keystore/debug.keystore
Labels: 🌀 민서, ➕ Add

#152 [Docs/#151] 리드미 추가 작성
  README.md
Labels: 😎 종우

#154 [Feat/#131] 홈화면 api 연결
  app/src/main/java/org/sopt/certi/data/mapper/todomain/cert/FavoriteResponseDtoMapper.kt
  app/src/main/java/org/sopt/certi/data/mapper/todomain/cert/PreCertResponseDtoMapper.kt
  app/src/main/java/org/sopt/certi/data/mapper/todomain/user/UserInfoResponseDtoMapper.kt
  app/src/main/java/org/sopt/certi/data/remote/datasource/HomeRemoteDataSource.kt
  app/src/main/java/org/sopt/certi/data/remote/datasourceimpl/HomeRemoteDataSourceImpl.kt
  app/src/main/java/org/sopt/certi/data/remote/dto/response/FavoriteListResponseDto.kt
  app/src/main/java/org/sopt/certi/data/remote/dto/response/PreCertResponseDto.kt
  app/src/main/java/org/sopt/certi/data/remote/dto/response/UserInfoResponseDto.kt
  app/src/main/java/org/sopt/certi/data/remote/service/HomeService.kt
  app/src/main/java/org/sopt/certi/data/repositoryimpl/HomeRepositoryImpl.kt
  app/src/main/java/org/sopt/certi/di/DataSourceModule.kt
  app/src/main/java/org/sopt/certi/di/RepositoryModule.kt
  app/src/main/java/org/sopt/certi/di/ServiceModule.kt
  app/src/main/java/org/sopt/certi/di/UseCaseModule.kt
  app/src/main/java/org/sopt/certi/domain/repository/HomeRepository.kt
  app/src/main/java/org/sopt/certi/domain/usecase/FavoriteUseCase.kt
  app/src/main/java/org/sopt/certi/domain/usecase/HomeRecommendUseCase.kt
  app/src/main/java/org/sopt/certi/domain/usecase/PreCertUseCase.kt
  app/src/main/java/org/sopt/certi/domain/usecase/ToggleFavoriteUseCase.kt
  app/src/main/java/org/sopt/certi/domain/usecase/UserInfoUseCase.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/HomeViewModel.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/PreCertificationEditScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/component/FavoriteCertificationItem.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/component/RecommendedCertificationItem.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/state/HomeUiState.kt
  app/src/main/java/org/sopt/certi/presentation/ui/precertificationedit/component/PreCertificationItem.kt
Labels: ✨ Feat, 💻 API 연결, 💜 민지

#161 [Feat #132] 로딩 온보딩에도 적용
  app/src/main/java/org/sopt/certi/core/component/loading/Loading.kt
  app/src/main/java/org/sopt/certi/presentation/ui/onboarding/OnBoardingInfoScreen.kt
Labels: ✨ Feat, 🔎 UI, 😎 종우

#167 [Fix/#165] 온보딩, 검색 뷰 1차 QA 반영
  app/src/main/java/org/sopt/certi/core/component/textfield/CertiBasicTextField.kt
  app/src/main/java/org/sopt/certi/presentation/ui/search/SearchScreen.kt
Labels: 🌀 민서, 🛠️ Fix

#168 [Fix/#163] 이력서 뷰 1차 QA 적용
  app/src/main/java/org/sopt/certi/data/mapper/todomain/acquisition/AcquisitionListResponseMapper.kt
  app/src/main/java/org/sopt/certi/data/remote/dto/response/GetAcquisitionListResponseDto.kt
  app/src/main/java/org/sopt/certi/presentation/type/CertCardColorType.kt
  app/src/main/java/org/sopt/certi/presentation/ui/activity/ResumeAddActivitiesScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/ResumeScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/ResumeViewModel.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeAddButton.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeCertificationSection.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeCertificationSmallCard.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeDateInputSection.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeDescriptionSection.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeListSection.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeTextField.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/ResumeTextInputSection.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/card/CertificationCardBack.kt
  app/src/main/java/org/sopt/certi/presentation/ui/resume/component/card/FlipCard.kt
  app/src/main/java/org/sopt/certi/presentation/ui/workExperience/ResumeAddWorkExperienceScreen.kt
  app/src/main/res/values/strings.xml
Labels: 🛠️ Fix, 🍀 지현

#169 [Feat/#166] 홈화면 qa 1차 수정
  app/src/main/java/org/sopt/certi/core/navigation/RouteModel.kt
  app/src/main/java/org/sopt/certi/core/util/ModifierExt.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/component/FavoriteCertificationItem.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/navigation/HomeNavigation.kt
  app/src/main/java/org/sopt/certi/presentation/ui/precertificationedit/component/PreCertificationItem.kt
Labels: 🛠️ Fix, 💜 민지

#173 [Fix/#172] 1차 QA 최최종 반영했띠
  app/src/main/java/org/sopt/certi/presentation/ui/certdetail/CertDetailScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/HomeScreen.kt
  app/src/main/java/org/sopt/certi/presentation/ui/home/component/FavoriteCertificationItem.kt
  app/src/main/java/org/sopt/certi/presentation/ui/precertificationedit/component/PreCertificationItem.kt
  app/src/main/res/values/strings.xml
Labels: 🛠️ Fix, 🍀 지현
